
#if !defined(AFX_CONSOLEIO_H__D7E24FCA_F3A8_4FB6_BA17_08DECDC2168B__INCLUDED_)
#define AFX_CONSOLEIO_H__D7E24FCA_F3A8_4FB6_BA17_08DECDC2168B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include <windows.h>

/**************************************************************
*  Pre-defined values in wincon.h
***************************************************************
FOREGROUND_BLUE
FOREGROUND_GREEN
FOREGROUND_RED
FOREGROUND_INTENSITY

BACKGROUND_BLUE
BACKGROUND_GREEN
BACKGROUND_RED
BACKGROUND_INTENSITY
****************************************************************/

#define FOREGROUND_BLACK			0
#define FOREGROUND_GRAY				FOREGROUND_INTENSITY
#define FOREGROUND_YELLOW			FOREGROUND_RED | FOREGROUND_GREEN
#define FOREGROUND_AQUA				FOREGROUND_GREEN | FOREGROUND_BLUE
#define FOREGROUND_PURPLE			FOREGROUND_RED | FOREGROUND_BLUE
#define FOREGROUND_WHITE			FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE

#define FOREGROUND_LIGHTBLUE		FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define FOREGROUND_LIGHTGREEN		FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define FOREGROUND_LIGHTRED			FOREGROUND_RED | FOREGROUND_INTENSITY
#define FOREGROUND_LIGHTPURPLE		FOREGROUND_PURPLE | FOREGROUND_INTENSITY
#define FOREGROUND_LIGHTYELLOW		FOREGROUND_YELLOW | FOREGROUND_INTENSITY
#define FOREGROUND_LIGHTAQUA		FOREGROUND_AQUA | FOREGROUND_INTENSITY
#define FOREGROUND_BRIGHTWHITE		FOREGROUND_WHITE | FOREGROUND_INTENSITY

#define BACKGROUND_BLACK			0
#define BACKGROUND_GRAY				BACKGROUND_INTENSITY
#define BACKGROUND_YELLOW			BACKGROUND_RED | BACKGROUND_GREEN
#define BACKGROUND_AQUA				BACKGROUND_GREEN | BACKGROUND_BLUE
#define BACKGROUND_PURPLE			BACKGROUND_RED | BACKGROUND_BLUE
#define BACKGROUND_WHITE			BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE

#define BACKGROUND_LIGHTBLUE		BACKGROUND_BLUE | BACKGROUND_INTENSITY
#define BACKGROUND_LIGHTGREEN		BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define BACKGROUND_LIGHTRED			BACKGROUND_RED | BACKGROUND_INTENSITY
#define BACKGROUND_LIGHTPURPLE		BACKGROUND_PURPLE | BACKGROUND_INTENSITY
#define BACKGROUND_LIGHTYELLOW		BACKGROUND_YELLOW | BACKGROUND_INTENSITY
#define BACKGROUND_LIGHTAQUA		BACKGROUND_AQUA | BACKGROUND_INTENSITY
#define BACKGROUND_BRIGHTWHITE		BACKGROUND_WHITE | BACKGROUND_INTENSITY


class CConsoleIO  
{
public:
	CConsoleIO();
	virtual ~CConsoleIO();

	static WORD m_wAttribute;
	
	void SetColourAttributes(WORD);
	WORD GetColourAttributes(void);

	void ClearScreen();
	void ClearScreen(int l, int t, int r, int b);
	void ClearEndOfLine();
	
	void  GotoStartOfLine();
	COORD GetCursorPos();
	void  SetCursorPos(COORD);
	void  SetCursorPos(short,short);
	void  SetCursorX(int);
	void  SetCursorY(int);

	void PushColourAttributes(void);
	void PopColourAttributes(void);

protected:

	HANDLE m_hConsole;
};

#endif // !defined(AFX_CONSOLEIO_H__D7E24FCA_F3A8_4FB6_BA17_08DECDC2168B__INCLUDED_)
